# Site wide configuration
theme: jekyll-theme-minimal

title: Artes
locale: en_US
description: _The history of the growth and development of Los Angeles... reveals its conscious use of water as a tool to build the “great metropolis of the Pacific”_ -- Vincent Ostrom, 1962 
url: https://github.com/erikporse/artes


# Site owner
owner:
  name: Erik Porse