# Site wide configuration
theme: jekyll-theme-cayman

title: Artes
locale: en_US
description: A A model for integrated water supply management in L.A. County
url: https://github.com/erikporse/artes


# Site owner
owner:
  name: Erik Porse
  
theme: jekyll-theme-cayman