# Site wide configuration
theme: jekyll-theme-minimal

title: Artes
locale: en_US
description: A model of urban water resources management in Los Angeles
url: https://github.com/erikporse/artes


# Site owner
owner:
  name: Erik Porse