# Site wide configuration
theme: jekyll-theme-midnight

title: Artes
locale: en_US
description: A model for integrated water supply management in L.A. County
url: https://github.com/erikporse/artes


# Site owner
owner:
  name: Erik Porse